// Generated by buildinfo
//
// DO NOT EDIT!

package libflux

// sourceHashes is the hash of the build sources for
// the rust components used by cgo.
// This gets generated from the libflux sources
// and forces the cgo library to rebuild and relink
// the sources. This is because non-C/C++ sources
// are not tracked by Go's build system.'
//lint:ignore U1000 generated code
var sourceHashes = map[string]string{
	"libflux/Cargo.lock":                                                                          "18cfe463bc9e38c2c96ae1f2a5d90c7fa98334d1f53098c1b48061e297b7f64a",
	"libflux/Cargo.toml":                                                                          "91ac4e8b467440c6e8a9438011de0e7b78c2732403bb067d4dd31539ac8a90c1",
	"libflux/flux-core/Cargo.toml":                                                                "b143cfaa42f118282b28d45839bd97e0f769a8b87e1dbb20320e9cd54f1115cc",
	"libflux/flux-core/benches/scanner.rs":                                                        "da73723114b3a22ef3f497fbc7bf9b93b4ddc1e38d31d0fee974e027fb45f199",
	"libflux/flux-core/src/ast/check/mod.rs":                                                      "ea93aaf47bded6f1fa46f6167308750837fac20a7e5ddeaecc86a3bc855143a4",
	"libflux/flux-core/src/ast/check/tests.rs":                                                    "d1bc09d1f2573d4addd546a6fbf2ca7c9a65d0dd773b687196a5a3df4f2fd299",
	"libflux/flux-core/src/ast/flatbuffers/ast_generated.rs":                                      "895e09284030a8ea05883fbb71d67282a6b567678126f2e2aadfc5bca72ed47d",
	"libflux/flux-core/src/ast/flatbuffers/mod.rs":                                                "cb94deda98a8aa03199e3fa6b8e0e85b0890ff312a0eb36bc3fcc7cc12665eeb",
	"libflux/flux-core/src/ast/flatbuffers/monotype.rs":                                           "4e82aae8e7edb8e230302241fe702ece9ae84fc708003c24709c2ea944cfaae8",
	"libflux/flux-core/src/ast/flatbuffers/tests.rs":                                              "c20dde15a795e714ef819c4f031ee6502fff50f6cc47883afa39f6e2dd2c7f74",
	"libflux/flux-core/src/ast/mod.rs":                                                            "b187cc8b46f702e5caa86f767e9849d5c6c3c2ae51008543ee5fb9f81e247491",
	"libflux/flux-core/src/ast/tests.rs":                                                          "3011e32024ade431de02f94cd5e14e5fa8df87754c995da126c2f33d1168507d",
	"libflux/flux-core/src/ast/walk/mod.rs":                                                       "e8a03023d7426bcf6dfdb1a61ac3263f5cf9194a595a1584dff7c899d06562f1",
	"libflux/flux-core/src/ast/walk/tests.rs":                                                     "54e417affc95ef9887860c54f65b6d8fd7f41ccc13e2a5fa9d7452296364d629",
	"libflux/flux-core/src/bin/fluxc.rs":                                                          "68d16ddef3a6c6f6db04a969cef91a0e22ee74ecc52e5f57905fde88ae2da87b",
	"libflux/flux-core/src/bin/fluxdoc.rs":                                                        "71b12ecba4240daeaa086f31250253b2613aaa5aa8bb71ea1685695717680e42",
	"libflux/flux-core/src/formatter/mod.rs":                                                      "ce8396fb867a5bc361fec99c36d36d70d2e1f3a6ec12de714f7257e4d4eef57f",
	"libflux/flux-core/src/formatter/tests.rs":                                                    "b0a10998a65fc4b54a8f68b3a0ed186d8548ba3d7638f911eb188d2ce485206f",
	"libflux/flux-core/src/lib.rs":                                                                "b15c8350169ed94973b173eb80f49e6d737e081501a28f66b979b60ec377028e",
	"libflux/flux-core/src/parser/mod.rs":                                                         "1d5862788873ddf06599e592b68445c9d398b46cdbfb2c2d3590c6a338d78cde",
	"libflux/flux-core/src/parser/strconv.rs":                                                     "748c82f6efc2eafaafb872db5b4185ce29aafa8f03ba02c4b84f4a9614e832d2",
	"libflux/flux-core/src/parser/tests.rs":                                                       "1277c672801f50eefd36ddfae4ce8456c5ddcfbe63f4b1923f1aecbb2d9794c3",
	"libflux/flux-core/src/scanner/mod.rs":
